var routerApp = angular.module('LionApp', ['ui.router']);

routerApp.controller('appController', function($scope) {
    
    $scope.apps = [
        {"id":1,"name":"Wikibox","image":"http://dummyimage.com/115x107.png/5fa2dd/ffffff","address":"0 Towne Court","state":"California","operation_hours":"6:41 PM","phone":"1-(408)848-0500","status":true},
        {"id":2,"name":"Photobean","image":"http://dummyimage.com/238x101.png/dddddd/000000","address":"4 Sundown Crossing","state":"Illinois","operation_hours":"8:24 AM","phone":"1-(773)477-7160","status":false},
        {"id":3,"name":"Voonte","image":"http://dummyimage.com/224x208.bmp/dddddd/000000","address":"8 Caliangt Park","state":"Tennessee","operation_hours":"3:51 PM","phone":"1-(423)735-5236","status":false},
        {"id":4,"name":"Skaboo","image":"http://dummyimage.com/137x209.bmp/5fa2dd/ffffff","address":"18 Cottonwood Alley","state":"Illinois","operation_hours":"7:42 AM","phone":"1-(425)157-6819","status":false},
        {"id":5,"name":"Linkbuzz","image":"http://dummyimage.com/119x126.jpg/ff4444/ffffff","address":"826 Holmberg Park","state":"Florida","operation_hours":"4:31 AM","phone":"1-(330)731-7050","status":false},
        {"id":6,"name":"Tagopia","image":"http://dummyimage.com/114x244.png/dddddd/000000","address":"1 Anzinger Pass","state":"Delaware","operation_hours":"2:10 AM","phone":"1-(302)576-4313","status":false},
        {"id":7,"name":"Pixope","image":"http://dummyimage.com/203x179.jpg/5fa2dd/ffffff","address":"5505 Welch Alley","state":"Florida","operation_hours":"4:59 PM","phone":"1-(321)372-8359","status":false},
        {"id":8,"name":"Twimm","image":"http://dummyimage.com/142x213.png/5fa2dd/ffffff","address":"03293 Burning Wood Court","state":"North Carolina","operation_hours":"1:14 PM","phone":"1-(919)193-4776","status":true},
        {"id":9,"name":"Vinte","image":"http://dummyimage.com/149x197.bmp/cc0000/ffffff","address":"3953 Cottonwood Pass","state":"Indiana","operation_hours":"1:04 AM","phone":"1-(317)297-9710","status":false},
        {"id":10,"name":"Snaptags","image":"http://dummyimage.com/223x134.png/cc0000/ffffff","address":"769 Roxbury Park","state":"Florida","operation_hours":"4:34 PM","phone":"1-(912)183-5785","status":false},
        {"id":11,"name":"Flipopia","image":"http://dummyimage.com/113x197.jpg/ff4444/ffffff","address":"08 Declaration Center","state":"Texas","operation_hours":"10:04 PM","phone":"1-(254)613-0760","status":true},
        {"id":12,"name":"Skidoo","image":"http://dummyimage.com/209x206.jpg/cc0000/ffffff","address":"0 Delaware Street","state":"California","operation_hours":"2:36 PM","phone":"1-(619)545-8127","status":false},
        {"id":13,"name":"Talane","image":"http://dummyimage.com/182x233.png/ff4444/ffffff","address":"1 Warbler Plaza","state":"California","operation_hours":"5:55 AM","phone":"1-(626)600-3295","status":true},
        {"id":14,"name":"Mynte","image":"http://dummyimage.com/152x200.png/5fa2dd/ffffff","address":"7 Vidon Court","state":"California","operation_hours":"3:53 PM","phone":"1-(323)199-6497","status":false},
        {"id":15,"name":"Yodoo","image":"http://dummyimage.com/175x203.png/ff4444/ffffff","address":"2 Briar Crest Hill","state":"Texas","operation_hours":"9:41 AM","phone":"1-(817)819-4380","status":true},
        {"id":16,"name":"Layo","image":"http://dummyimage.com/240x120.bmp/5fa2dd/ffffff","address":"8521 Jenna Drive","state":"Texas","operation_hours":"7:45 PM","phone":"1-(915)133-3619","status":false},
        {"id":17,"name":"Youfeed","image":"http://dummyimage.com/237x145.jpg/cc0000/ffffff","address":"6 Hoard Center","state":"Louisiana","operation_hours":"4:45 PM","phone":"1-(504)281-2864","status":true},
        {"id":18,"name":"Gabtype","image":"http://dummyimage.com/169x217.png/ff4444/ffffff","address":"67094 Green Ridge Court","state":"California","operation_hours":"8:42 AM","phone":"1-(213)657-2168","status":true},
        {"id":19,"name":"Dabvine","image":"http://dummyimage.com/166x168.jpg/dddddd/000000","address":"260 Grasskamp Avenue","state":"Illinois","operation_hours":"9:45 PM","phone":"1-(312)183-3991","status":true},
        {"id":20,"name":"Reallinks","image":"http://dummyimage.com/195x182.jpg/cc0000/ffffff","address":"2616 Ohio Street","state":"Oklahoma","operation_hours":"6:28 AM","phone":"1-(405)601-0929","status":true},
        {"id":21,"name":"Bluezoom","image":"http://dummyimage.com/119x182.bmp/dddddd/000000","address":"971 Comanche Lane","state":"Pennsylvania","operation_hours":"8:09 AM","phone":"1-(814)313-4376","status":true},
        {"id":22,"name":"Browsezoom","image":"http://dummyimage.com/221x183.png/dddddd/000000","address":"2 Susan Lane","state":"New York","operation_hours":"7:24 AM","phone":"1-(718)940-2715","status":false},
        {"id":23,"name":"Realbuzz","image":"http://dummyimage.com/169x109.jpg/dddddd/000000","address":"97886 Mosinee Street","state":"Tennessee","operation_hours":"6:09 PM","phone":"1-(615)766-3469","status":true},
        {"id":24,"name":"Eabox","image":"http://dummyimage.com/237x136.bmp/dddddd/000000","address":"905 Thierer Hill","state":"Colorado","operation_hours":"2:33 PM","phone":"1-(303)114-8029","status":false},
        {"id":25,"name":"Rhynyx","image":"http://dummyimage.com/152x137.jpg/cc0000/ffffff","address":"864 Dayton Avenue","state":"Texas","operation_hours":"4:46 AM","phone":"1-(713)369-1558","status":false},
        {"id":26,"name":"Pixonyx","image":"http://dummyimage.com/157x154.jpg/dddddd/000000","address":"60 Ridgeway Center","state":"Alabama","operation_hours":"2:46 PM","phone":"1-(205)829-1256","status":true},
        {"id":27,"name":"Jazzy","image":"http://dummyimage.com/176x249.jpg/dddddd/000000","address":"3160 Mesta Alley","state":"Florida","operation_hours":"1:28 PM","phone":"1-(973)693-2264","status":false},
        {"id":28,"name":"Gabcube","image":"http://dummyimage.com/144x139.png/5fa2dd/ffffff","address":"07 Elgar Road","state":"Florida","operation_hours":"4:28 PM","phone":"1-(850)751-8267","status":false},
        {"id":29,"name":"Myworks","image":"http://dummyimage.com/155x130.png/cc0000/ffffff","address":"8 Rockefeller Drive","state":"Hawaii","operation_hours":"11:55 PM","phone":"1-(808)423-0006","status":true},
        {"id":30,"name":"Livefish","image":"http://dummyimage.com/206x154.png/cc0000/ffffff","address":"25 Maple Place","state":"California","operation_hours":"11:23 AM","phone":"1-(661)837-1557","status":true}
        ]

    $scope.countries = [ 
        {name: 'Afghanistan', code: 'AF'},
        {name: 'Åland Islands', code: 'AX'},
        {name: 'Albania', code: 'AL'},
        {name: 'Algeria', code: 'DZ'},
        {name: 'American Samoa', code: 'AS'},
        {name: 'Andorra', code: 'AD'},
        {name: 'Angola', code: 'AO'},
        {name: 'Anguilla', code: 'AI'},
        {name: 'Antarctica', code: 'AQ'},
        {name: 'Antigua and Barbuda', code: 'AG'},
        {name: 'Argentina', code: 'AR'},
        {name: 'Armenia', code: 'AM'},
        {name: 'Aruba', code: 'AW'},
        {name: 'Australia', code: 'AU'},
        {name: 'Austria', code: 'AT'},
        {name: 'Azerbaijan', code: 'AZ'},
        {name: 'Bahamas', code: 'BS'},
        {name: 'Bahrain', code: 'BH'},
        {name: 'Bangladesh', code: 'BD'},
        {name: 'Barbados', code: 'BB'},
        {name: 'Belarus', code: 'BY'},
        {name: 'Belgium', code: 'BE'},
        {name: 'Belize', code: 'BZ'},
        {name: 'Benin', code: 'BJ'},
        {name: 'Bermuda', code: 'BM'},
        {name: 'Bhutan', code: 'BT'},
        {name: 'Bolivia', code: 'BO'},
        {name: 'Bosnia and Herzegovina', code: 'BA'},
        {name: 'Botswana', code: 'BW'},
        {name: 'Bouvet Island', code: 'BV'},
        {name: 'Brazil', code: 'BR'},
        {name: 'British Indian Ocean Territory', code: 'IO'},
        {name: 'Brunei Darussalam', code: 'BN'},
        {name: 'Bulgaria', code: 'BG'},
        {name: 'Burkina Faso', code: 'BF'},
        {name: 'Burundi', code: 'BI'},
        {name: 'Cambodia', code: 'KH'},
        {name: 'Cameroon', code: 'CM'},
        {name: 'Canada', code: 'CA'},
        {name: 'Cape Verde', code: 'CV'},
        {name: 'Cayman Islands', code: 'KY'},
        {name: 'Central African Republic', code: 'CF'},
        {name: 'Chad', code: 'TD'},
        {name: 'Chile', code: 'CL'},
        {name: 'China', code: 'CN'},
        {name: 'Christmas Island', code: 'CX'},
        {name: 'Cocos (Keeling) Islands', code: 'CC'},
        {name: 'Colombia', code: 'CO'},
        {name: 'Comoros', code: 'KM'},
        {name: 'Congo', code: 'CG'},
        {name: 'Congo, The Democratic Republic of the', code: 'CD'},
        {name: 'Cook Islands', code: 'CK'},
        {name: 'Costa Rica', code: 'CR'},
        {name: 'Cote D\'Ivoire', code: 'CI'},
        {name: 'Croatia', code: 'HR'},
        {name: 'Cuba', code: 'CU'},
        {name: 'Cyprus', code: 'CY'},
        {name: 'Czech Republic', code: 'CZ'},
        {name: 'Denmark', code: 'DK'},
        {name: 'Djibouti', code: 'DJ'},
        {name: 'Dominica', code: 'DM'},
        {name: 'Dominican Republic', code: 'DO'},
        {name: 'Ecuador', code: 'EC'},
        {name: 'Egypt', code: 'EG'},
        {name: 'El Salvador', code: 'SV'},
        {name: 'Equatorial Guinea', code: 'GQ'},
        {name: 'Eritrea', code: 'ER'},
        {name: 'Estonia', code: 'EE'},
        {name: 'Ethiopia', code: 'ET'},
        {name: 'Falkland Islands (Malvinas)', code: 'FK'},
        {name: 'Faroe Islands', code: 'FO'},
        {name: 'Fiji', code: 'FJ'},
        {name: 'Finland', code: 'FI'},
        {name: 'France', code: 'FR'},
        {name: 'French Guiana', code: 'GF'},
        {name: 'French Polynesia', code: 'PF'},
        {name: 'French Southern Territories', code: 'TF'},
        {name: 'Gabon', code: 'GA'},
        {name: 'Gambia', code: 'GM'},
        {name: 'Georgia', code: 'GE'},
        {name: 'Germany', code: 'DE'},
        {name: 'Ghana', code: 'GH'},
        {name: 'Gibraltar', code: 'GI'},
        {name: 'Greece', code: 'GR'},
        {name: 'Greenland', code: 'GL'},
        {name: 'Grenada', code: 'GD'},
        {name: 'Guadeloupe', code: 'GP'},
        {name: 'Guam', code: 'GU'},
        {name: 'Guatemala', code: 'GT'},
        {name: 'Guernsey', code: 'GG'},
        {name: 'Guinea', code: 'GN'},
        {name: 'Guinea-Bissau', code: 'GW'},
        {name: 'Guyana', code: 'GY'},
        {name: 'Haiti', code: 'HT'},
        {name: 'Heard Island and Mcdonald Islands', code: 'HM'},
        {name: 'Holy See (Vatican City State)', code: 'VA'},
        {name: 'Honduras', code: 'HN'},
        {name: 'Hong Kong', code: 'HK'},
        {name: 'Hungary', code: 'HU'},
        {name: 'Iceland', code: 'IS'},
        {name: 'India', code: 'IN'},
        {name: 'Indonesia', code: 'ID'},
        {name: 'Iran, Islamic Republic Of', code: 'IR'},
        {name: 'Iraq', code: 'IQ'},
        {name: 'Ireland', code: 'IE'},
        {name: 'Isle of Man', code: 'IM'},
        {name: 'Israel', code: 'IL'},
        {name: 'Italy', code: 'IT'},
        {name: 'Jamaica', code: 'JM'},
        {name: 'Japan', code: 'JP'},
        {name: 'Jersey', code: 'JE'},
        {name: 'Jordan', code: 'JO'},
        {name: 'Kazakhstan', code: 'KZ'},
        {name: 'Kenya', code: 'KE'},
        {name: 'Kiribati', code: 'KI'},
        {name: 'Korea, Democratic People\'s Republic of', code: 'KP'},
        {name: 'Korea, Republic of', code: 'KR'},
        {name: 'Kuwait', code: 'KW'},
        {name: 'Kyrgyzstan', code: 'KG'},
        {name: 'Lao People\'s Democratic Republic', code: 'LA'},
        {name: 'Latvia', code: 'LV'},
        {name: 'Lebanon', code: 'LB'},
        {name: 'Lesotho', code: 'LS'},
        {name: 'Liberia', code: 'LR'},
        {name: 'Libyan Arab Jamahiriya', code: 'LY'},
        {name: 'Liechtenstein', code: 'LI'},
        {name: 'Lithuania', code: 'LT'},
        {name: 'Luxembourg', code: 'LU'},
        {name: 'Macao', code: 'MO'},
        {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK'},
        {name: 'Madagascar', code: 'MG'},
        {name: 'Malawi', code: 'MW'},
        {name: 'Malaysia', code: 'MY'},
        {name: 'Maldives', code: 'MV'},
        {name: 'Mali', code: 'ML'},
        {name: 'Malta', code: 'MT'},
        {name: 'Marshall Islands', code: 'MH'},
        {name: 'Martinique', code: 'MQ'},
        {name: 'Mauritania', code: 'MR'},
        {name: 'Mauritius', code: 'MU'},
        {name: 'Mayotte', code: 'YT'},
        {name: 'Mexico', code: 'MX'},
        {name: 'Micronesia, Federated States of', code: 'FM'},
        {name: 'Moldova, Republic of', code: 'MD'},
        {name: 'Monaco', code: 'MC'},
        {name: 'Mongolia', code: 'MN'},
        {name: 'Montserrat', code: 'MS'},
        {name: 'Morocco', code: 'MA'},
        {name: 'Mozambique', code: 'MZ'},
        {name: 'Myanmar', code: 'MM'},
        {name: 'Namibia', code: 'NA'},
        {name: 'Nauru', code: 'NR'},
        {name: 'Nepal', code: 'NP'},
        {name: 'Netherlands', code: 'NL'},
        {name: 'Netherlands Antilles', code: 'AN'},
        {name: 'New Caledonia', code: 'NC'},
        {name: 'New Zealand', code: 'NZ'},
        {name: 'Nicaragua', code: 'NI'},
        {name: 'Niger', code: 'NE'},
        {name: 'Nigeria', code: 'NG'},
        {name: 'Niue', code: 'NU'},
        {name: 'Norfolk Island', code: 'NF'},
        {name: 'Northern Mariana Islands', code: 'MP'},
        {name: 'Norway', code: 'NO'},
        {name: 'Oman', code: 'OM'},
        {name: 'Pakistan', code: 'PK'},
        {name: 'Palau', code: 'PW'},
        {name: 'Palestinian Territory, Occupied', code: 'PS'},
        {name: 'Panama', code: 'PA'},
        {name: 'Papua New Guinea', code: 'PG'},
        {name: 'Paraguay', code: 'PY'},
        {name: 'Peru', code: 'PE'},
        {name: 'Philippines', code: 'PH'},
        {name: 'Pitcairn', code: 'PN'},
        {name: 'Poland', code: 'PL'},
        {name: 'Portugal', code: 'PT'},
        {name: 'Puerto Rico', code: 'PR'},
        {name: 'Qatar', code: 'QA'},
        {name: 'Reunion', code: 'RE'},
        {name: 'Romania', code: 'RO'},
        {name: 'Russian Federation', code: 'RU'},
        {name: 'Rwanda', code: 'RW'},
        {name: 'Saint Helena', code: 'SH'},
        {name: 'Saint Kitts and Nevis', code: 'KN'},
        {name: 'Saint Lucia', code: 'LC'},
        {name: 'Saint Pierre and Miquelon', code: 'PM'},
        {name: 'Saint Vincent and the Grenadines', code: 'VC'},
        {name: 'Samoa', code: 'WS'},
        {name: 'San Marino', code: 'SM'},
        {name: 'Sao Tome and Principe', code: 'ST'},
        {name: 'Saudi Arabia', code: 'SA'},
        {name: 'Senegal', code: 'SN'},
        {name: 'Serbia and Montenegro', code: 'CS'},
        {name: 'Seychelles', code: 'SC'},
        {name: 'Sierra Leone', code: 'SL'},
        {name: 'Singapore', code: 'SG'},
        {name: 'Slovakia', code: 'SK'},
        {name: 'Slovenia', code: 'SI'},
        {name: 'Solomon Islands', code: 'SB'},
        {name: 'Somalia', code: 'SO'},
        {name: 'South Africa', code: 'ZA'},
        {name: 'South Georgia and the South Sandwich Islands', code: 'GS'},
        {name: 'Spain', code: 'ES'},
        {name: 'Sri Lanka', code: 'LK'},
        {name: 'Sudan', code: 'SD'},
        {name: 'Suriname', code: 'SR'},
        {name: 'Svalbard and Jan Mayen', code: 'SJ'},
        {name: 'Swaziland', code: 'SZ'},
        {name: 'Sweden', code: 'SE'},
        {name: 'Switzerland', code: 'CH'},
        {name: 'Syrian Arab Republic', code: 'SY'},
        {name: 'Taiwan, Province of China', code: 'TW'},
        {name: 'Tajikistan', code: 'TJ'},
        {name: 'Tanzania, United Republic of', code: 'TZ'},
        {name: 'Thailand', code: 'TH'},
        {name: 'Timor-Leste', code: 'TL'},
        {name: 'Togo', code: 'TG'},
        {name: 'Tokelau', code: 'TK'},
        {name: 'Tonga', code: 'TO'},
        {name: 'Trinidad and Tobago', code: 'TT'},
        {name: 'Tunisia', code: 'TN'},
        {name: 'Turkey', code: 'TR'},
        {name: 'Turkmenistan', code: 'TM'},
        {name: 'Turks and Caicos Islands', code: 'TC'},
        {name: 'Tuvalu', code: 'TV'},
        {name: 'Uganda', code: 'UG'},
        {name: 'Ukraine', code: 'UA'},
        {name: 'United Arab Emirates', code: 'AE'},
        {name: 'United Kingdom', code: 'GB'},
        {name: 'United States', code: 'US'},
        {name: 'United States Minor Outlying Islands', code: 'UM'},
        {name: 'Uruguay', code: 'UY'},
        {name: 'Uzbekistan', code: 'UZ'},
        {name: 'Vanuatu', code: 'VU'},
        {name: 'Venezuela', code: 'VE'},
        {name: 'Vietnam', code: 'VN'},
        {name: 'Virgin Islands, British', code: 'VG'},
        {name: 'Virgin Islands, U.S.', code: 'VI'},
        {name: 'Wallis and Futuna', code: 'WF'},
        {name: 'Western Sahara', code: 'EH'},
        {name: 'Yemen', code: 'YE'},
        {name: 'Zambia', code: 'ZM'},
        {name: 'Zimbabwe', code: 'ZW'}
    ];
});

